---
- hosts: all
  tasks:
    
    - name: install httpd,postfix
      yum:
        name: httpd,mariadb,postfix
        state: latest
        
        
    - service:
        name: "{{ item }}"
        state: started
        enabled: yes

      loop:
        - httpd
        - postfix

...          
