---
- name: Start and enable Apache  Service
  hosts: all   
  tasks:
    
    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
    

    - name: Enable service httpd, and not touch the state
      service:
        name: httpd
        enabled: yes

...

