---
- name: Stop Apache Service
  hosts: all   
  tasks:
    
    - name: Stop httpd
      service:
        name: httpd
        state: stopped
    

    - name: disable service httpd
      service:
        name: httpd
        enabled: no

...

