---
- name: controlling task using when
  hosts: all
  tasks:
    - name: create multiple users with different password in mhost1
      user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.pass | password_hash('sha512') }}"
      loop:
        
        - name: user1
          pass: oracle123
        - name: user2
          pass: oracle123
        - name: user3
          pass: oracle123
      when: inventory_hostname == 'mhost2'   
