---
- name: Install httpd php 
  hosts: prod
  tasks:
    - name: Install httpd php pkgs
      yum:
        name: httpd,php
        state: latest
    - name: Start and enable service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Allow firewall rule for http
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: Create a Home page
      copy:
        content: My Oracle Site
        dest: /var/www/html/index.html
      notify: ReStart service

  handlers:
    - name: ReStart service
      service:
        name: httpd
        state: restarted

...
