---
- hosts: prod
  vars_files:
      - myusers.yml
  tasks:
    - name: Create a group
      group:
        name: aidu
        state: present

    - name: create a user
      user:
        name: aidu
        comment: aiden antony
        uid: 1041
        group: aidu
        state: present
        password: "{{ pass_aidu | password_hash('sha512') }}"
...
